# Generated by Django 2.1.2 on 2018-10-30 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=13, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('mensaje', models.CharField(max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('raza', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Registrado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=13, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('rut', models.CharField(max_length=13, null=True)),
                ('fechaNacimiento', models.DateTimeField(null=True)),
                ('telefono', models.IntegerField(null=True)),
                ('calle', models.CharField(max_length=13, null=True)),
                ('numero', models.CharField(max_length=13, null=True)),
            ],
        ),
    ]
