# Generated by Django 2.1.2 on 2018-10-24 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registrado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=13, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('rut', models.CharField(max_length=13, null=True)),
                ('fechaNacimiento', models.DateTimeField(null=True)),
                ('telefono', models.IntegerField(null=True)),
                ('region', models.CharField(max_length=13, null=True)),
                ('ciudad', models.CharField(max_length=13, null=True)),
                ('tipoVivienda', models.CharField(max_length=13, null=True)),
            ],
        ),
    ]
