# Generated by Django 2.1.2 on 2018-10-26 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_mascota'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mascota',
            name='foto',
        ),
    ]
