# Generated by Django 2.1.2 on 2018-10-26 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_mascota_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=13, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('mensaje', models.CharField(max_length=300, null=True)),
            ],
        ),
    ]
